sudo: false

os:
  - linux

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install numpy
  - pip install pandas
  - pip install tdml
  - pip install pytest
  - pip install torch==1.6.0+cpu

script:
  - cd tests
  - pytest test_dataset/test_dataset_numpy.py
  - pytest test_data/test_data_numpy.py
  - pytest test_dataset/test_dataset_pytorch.py
  - pytest test_data/test_data_pytorch.py
